name: Build

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with maven
      run: mvn clean compile

    - uses: actions/upload-artifact@master
      with:
        name: j4ts-example-bundle.js
        path: target/j4ts-example-bundle.js
        
        
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: j4ts-example-bundle.js
        path: j4ts-example-bundle.js

    - run: node j4ts-example-bundle.js
