name: Build

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Test
      run: node -v
      
    - name: Test 2
      run: cat 'console.log("coucou");' > test.js
      
    - name: Test 3
      run: node  test.js
      

    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with maven
      run: mvn clean compile

    - uses: actions/upload-artifact@master
      with:
        name: j4ts-example-bundle.js
        path: target/j4ts-example-bundle.js
        
    - name: Run tests file
      run: node j4ts-example-bundle.js
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download JS file
      uses: actions/download-artifact@master
      with:
        name: j4ts-example-bundle.js
        path: j4ts-example-bundle.js
    
    - name: pwd
      run: pwd
    - name: ls
      run: ls -alih
      
    - name: Run tests file
      run: node j4ts-example-bundle.js
